# use:
    # docker build -f Dockerfile.txt -t mlops_hw4 . && docker run --rm --name mlops_hw4  -it mlops_hw4

FROM agrigorev/zoomcamp-model:mlops-3.9.7-slim

WORKDIR /app
# COPY [ "model2.bin", "model.bin" ]

COPY ["Pipfile", "Pipfile.lock", "starter.py", "./"]
COPY ["data", "./data"]
RUN pip install pipenv
RUN pipenv install --system --deploy
RUN mkdir output
ENTRYPOINT ["python", "starter.py", "tripdata", "2021", "4"]
# ENTRYPOINT [ "bash" ]


