[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-final-newline",
    "missing-final-newline",
    "invalid-name",
    "too-few-public-methods",
    "line-too-long"
]