version: '3.3'
services:
    # docker run --rm --name mlflow5 -v /tmp/mlopsdb:/tmp/mlopsdb -v /tmp/mlopsartifacts:/tmp/mlopsartifacts -p 5051:5050 mlflow_4
    mlflow_server:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile-mlflow
        # args:
        #   buildno: 1
      image: mlflow_server
      container_name: mlflow_server
      ports:
        - 5051:5050
      networks:
        - backend
      # create these folders locally:
      volumes:
        - /tmp/mlopsdb:/tmp/mlopsdb
        - /tmp/mlopsartifacts:/tmp/mlopsartifacts
        - /tmp/store:/tmp/store

    prefect_server:
      # docker run --rm --name prefectTest3 -p 4200:4200 -p 8080:8080 prefect_test3 
      restart: always
      build:
        context: .
        dockerfile: Dockerfile-prefect
      logging:
        driver: none
      image: "prefect_server"
      container_name: "prefect_server"
      ports:
        - "4200:4200"
        - "8080:8080"
      networks:
        - backend  
      volumes:
        - /tmp/mlopsdb:/tmp/mlopsdb
        - /tmp/mlopsartifacts:/tmp/mlopsartifacts  
        - /tmp/store:/tmp/store      

    agent:
      build: .
      restart: always
      depends_on:
        - prefect_server
        - localstack
        - mlflow_server
      build:
        context: .
        dockerfile: Dockerfile-prefect-agent
      image: "prefect_agent_1"
      container_name: "prefect_agent_1"
      # command: bash -c "sleep 9999999"
      # command: bash -c "prefect agent local start --name $$(uuid) --no-hostname-label --label development"
      volumes:
        - /tmp/mlopsdb:/tmp/mlopsdb
        - /tmp/mlopsartifacts:/tmp/mlopsartifacts
        - /tmp/store:/tmp/store
      networks:
        - backend  

    localstack:
      container_name: "localstack_main"
      image: localstack/localstack
      hostname: s3
      ports:
        - "4566:4566"            # LocalStack Gateway
        - "4510-4559:4510-4559"  # external services port range
        - "53:53"                # DNS config (only required for Pro)
        - "53:53/udp"            # DNS config (only required for Pro)
        - "443:443"              # LocalStack HTTPS Gateway (only required for Pro)
      environment:
        - SERVICES=s3
        - AWS_DEFAULT_REGION=eu-west-1
        - AWS_ACCESS_KEY_ID=ID1
        - LOCALSTACK_HOSTNAME=s3
        # - AWS_SECRET_ACCESS_KEY=KEY1
        # - DEBUG=${DEBUG-}
        # - PERSISTENCE=${PERSISTENCE-}
        # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
        # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
        # - DOCKER_HOST=unix:///var/run/docker.sock
      # volumes:
      #   - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      #   - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
        - backend  

    # serve:
    #   build: .
    #   restart: always
    #   depends_on:
    #     - prefect_server
    #     - localstack
    #     - mlflow_server
    #     - agent
    #   build:
    #     context: .
    #     dockerfile: Dockerfile-serve
    #   image: "serve"
    #   container_name: "serve"
    #   ports:
    #     - "9696:9696"
    #   environment:
    #     - RUN_ID=541c7963880041319d17d2ee7a38003b
    #   volumes:
    #     - /tmp/mlopsdb:/tmp/mlopsdb
    #     - /tmp/mlopsartifacts:/tmp/mlopsartifacts
    #     - /tmp/store:/tmp/store
    #     - /tmp/serve:/tmp/serve
    #   networks:
    #     - backend  


networks:
    backend:
        driver: bridge
