FROM python:3.8

RUN pip install --no-cache-dir prefect==2.0b5

RUN mkdir /tmp/store

EXPOSE 4200
EXPOSE 8080

CMD printenv && prefect config set PREFECT_ORION_UI_API_URL="http://$CLOUD_ADDRESS:4200/api" && prefect orion start --host 0.0.0.0

