FROM python:3.8

COPY Pipfile* .

RUN apt update && apt install uuid -y
RUN pip install pipenv

RUN pip install --no-cache-dir prefect==2.0b5

RUN pipenv install

RUN pipenv run prefect config set PREFECT_ORION_UI_API_URL="http://prefect_server:4200/api"
RUN pipenv run prefect config set PREFECT_API_URL="http://prefect_server:4200/api"

RUN pipenv run prefect config view

ENTRYPOINT pipenv run prefect work-queue create work_queue_3 && pipenv run prefect agent start work_queue_3