version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    mongo_data: {}

networks:
    external:
      driver: bridge
    backend:
      driver: bridge

services:
  evidently_service:
    container_name: evidently_service
    image: evidently_service
    build:
      context: monitoring/evidently_service
      dockerfile: Dockerfile  
    depends_on:
      - grafana
    security_opt:
      - seccomp:unconfined
      - label:disable  
    volumes:
      - ./monitoring/evidently_service/datasets:/app/datasets
      - ./monitoring/evidently_service/config.yaml:/app/config.yaml
    ports:
      - "8085:8085"
    networks:
      - backend

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    security_opt:
      - seccomp:unconfined
      - label:disable  
    volumes:
      - ./monitoring/evidently_service/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9091:9090"
    networks:
      - backend
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    security_opt:
      - seccomp:unconfined
      - label:disable    
    volumes:
      - ./monitoring/evidently_service/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./monitoring/evidently_service/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./monitoring/evidently_service/dashboards:/opt/grafana/dashboards
      - ./monitoring/grafana_data:/var/lib/grafana
    networks:
      - backend
    restart: always
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    security_opt:
      - seccomp:unconfined
      - label:disable    
    volumes:
      - ./monitoring/mongo_data:/data/db
    networks:
      - backend


  serve:
    container_name: serve
    image: serve
    build: .
    restart: always
    depends_on:
      - prefect_server
      - localstack
      - mlflow_server
      - agent
      - evidently_service
      - mongo
    build:
      context: .
      dockerfile: Dockerfile-serve
    ports:
      - "9696:9696"
    env_file:
      - .env
    environment:
      EVIDENTLY_SERVICE: "http://evidently_service.:8085"
      MONGODB_ADDRESS: "mongodb://mongo:27017/"
      MLFLOW_ADDRESS: "http://mlflow_server:5050"
    volumes:
      - /tmp/mlopsdb:/tmp/mlopsdb
      - /tmp/mlopsartifacts:/tmp/mlopsartifacts
      - /tmp/store:/tmp/store
      - /tmp/serve:/tmp/serve
    networks:
      - backend  
      - external


  send_data:
    container_name: send_data
    image: send_data
    build: .
    restart: always
    depends_on:
      - serve
    build:
      context: .
      dockerfile: Dockerfile-send-data
    image: "send_data"
    container_name: "send_data"
    environment:
      SERVE_ADDRESS: "http://serve:9696"
    env_file:
      - .env
    networks:
      - external