FROM python:3.8

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN sh ./aws/install

COPY send_data-kinesis.py .
COPY input/ input_clean/


COPY setup_aws_credentials.sh .

CMD sh setup_aws_credentials.sh && python send_data-kinesis.py