FROM python:3.8

COPY requirements.txt .

RUN apt update && apt install uuid -y

RUN pip install --no-cache-dir prefect==2.0b5

RUN pip install -r requirements.txt

RUN prefect config set PREFECT_ORION_UI_API_URL="http://prefect_server:4200/api"
RUN prefect config set PREFECT_API_URL="http://prefect_server:4200/api"

RUN prefect config view

COPY orchestration/setup_prefect.sh .

ENTRYPOINT  sleep 15 && sh setup_prefect.sh && prefect agent start work_queue_3