version: '3.3'
services:
    mlflow_server:
        restart: always
        build:
          context: .
          dockerfile: Dockerfile-mlflow
          # args:
          #   buildno: 1
        image: mlflow_server
        container_name: mlflow_server
        ports:
            - 5051:5050
        networks:
            - frontend
            - backend
        # environment:
        volumes:
          - /tmp/mlopsdb:/tmp/mlopsdb

    # nginx:
    #     restart: always
    #     build: ./nginx
    #     image: mlflow_nginx
    #     container_name: mlflow_nginx
    #     ports:
    #         - "80:80"
    #     networks:
    #         - frontend
    #     depends_on:
    #         - web

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata: